// <auto-generated />
namespace LKS.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Singular : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Singular));
        
        string IMigrationMetadata.Id
        {
            get { return "201604041629460_Singular"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
